// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:product_view/models/product_model.dart';
import 'package:product_view/models/rating_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProductModelAdapter());
    registerAdapter(RatingModelAdapter());
  }
}
